export { EventsService } from './events.service'
export { Event } from './event.model'
export { TypesService } from './types.service'
export { Type } from './type.model'
export { AuthService } from './auth.service'
export { HomeService, EventData } from './home.service'
export { FavicoService } from './favico.service'
export { User } from './user.model'
